--- Cargo.toml.orig	2024-09-17 10:20:08 UTC
+++ Cargo.toml
@@ -38,7 +38,6 @@ zip = "2.1.3"
 zip = "2.1.3"
 
 [target.'cfg(unix)'.dependencies]
-openssl = { version = "0.10.64", features = ["vendored"] }
 
 [target.'cfg(windows)'.dependencies]
 winreg = "0.52.0"
